Vagrant.configure("2") do |config|
    config.vm.define "webserver" do |webserver|
        webserver.vm.box = "hashicorp-vagrant/ubuntu-16.04"
        webserver.vm.network :private_network, ip: "192.168.0.2"
        webserver.vm.hostname = "webserver"
        webserver.vm.provision "shell", path: "scripts/setup_ssh.sh"
    end
    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "hashicorp-vagrant/ubuntu-16.04"
	    ansible.vm.network :private_network, ip: "192.168.0.254"
	    ansible.vm.hostname = "ansible"
    end
    #config.vm.define "dnsserver" do |dnsserver|
    #    dnsserver.vm.box = "hashicorp-vagrant/ubuntu-16.04"
    #    dnsserver.vm.network :private_network, ip: "192.168.0.4"
	#    dnsserver.vm.hostname = "dnsserver"
    #end
end